[WIP] support multiple matched rules
pyama86/popper pull request #14
Opened 2018-07-25 04:13 UTC by akichan22

support multiple matched rules.

2018-07-27 14:02 UTC, pyama86 requested changes
なんかほぼできてそうな雰囲気。

2018-07-27 14:02 UTC, pyama86 commented on lib/popper/config.rb
> +      %w(find_all all?),
selectのほうが直感的で好みなのでselectでお願いします！

2018-07-27 14:02 UTC, pyama86 commented on lib/popper/mail_account.rb
> +      rules = match_rule?(mail)
match_rule?だと複数を想定しない名前なので、`match_rules`で行きましょう！

2018-07-28 02:16 UTC, akichan22 commented on lib/popper/config.rb
> +      %w(find_all all?),
確かに`select`の方が直感的ですね。
https://github.com/pyama86/popper/pull/14/commits/f2828c72c388c1cfb97af72d83050472cca16841 で修正しました!

2018-07-28 02:45 UTC, akichan22 commented on lib/popper/mail_account.rb
> +      rules = match_rule?(mail)
https://github.com/pyama86/popper/pull/14/commits/103a164bac4c4c0e6cf35ade489faf758c674626 こちらで修正しました!

2018-07-29 08:08 UTC, merged

2018-07-29 08:08 UTC, pyama86 commented
May the Force be with you